name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies for DAIRemote
      run: dotnet restore /p:EnableWindowsTargeting=true
      working-directory: DAIRemote

    - name: Build DAIRemote project
      run: dotnet build --no-restore /p:EnableWindowsTargeting=true
      working-directory: DAIRemote
    
    - name: Restore dependencies for DAIRemote.tests
      run: dotnet restore /p:EnableWindowsTargeting=true
      working-directory: DAIRemote.tests

    - name: Build DAIRemote.tests project
      run: dotnet build --no-restore /p:EnableWindowsTargeting=true
      working-directory: DAIRemote.tests

    - name: Test
      run: |
        if ($env:RUNNER_OS -eq "Windows") {
          dotnet test --no-build --verbosity normal --diagnostics /p:EnableWindowsTargeting=true
          }
      working-directory: DAIRemote.tests
